version: "2"
services:
  master:
    image: rabbitmq:3.7-management
    container_name: rmqha_node0
    restart: always
    mem_limit: 1024m
    hostname: rmqha_node0
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=rmqha_node0
      - RABBITMQ_HOSTNAME=rmqha_node0
      - RABBITMQ_NODENAME=rabbit
    extra_hosts:
      - "rmqha_node1:172.17.0.202"
      - "rmqha_node2:172.17.0.203"
    network_mode: "host"
