version: "2"
services:
  master:
    image: rabbitmq:3.6-management
    container_name: rmqha_node0
    restart: always
    mem_limit: 256m
    hostname: rmqha_node0
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=rmqha_node0
      - RABBITMQ_HOSTNAME=rmqha_node0
      - RABBITMQ_NODENAME=rabbit

  slave1:
    image: rabbitmq:3.6-management
    container_name: rmqha_node1
    restart: always
    depends_on:
      - master
    mem_limit: 256m
    hostname: rmqha_node1
    volumes:
      - "./volumes/rmqha_slave/cluster_entrypoint.sh:/usr/local/bin/cluster_entrypoint.sh"
    entrypoint: "/usr/local/bin/cluster_entrypoint.sh"
    command: "rabbitmq-server"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=rmqha_node1
      - RABBITMQ_HOSTNAME=rmqha_node1
      - RABBITMQ_NODENAME=rabbit
      - RMQHA_RAM_NODE=true

  slave2:
    image: rabbitmq:3.6-management
    container_name: rmqha_node2
    restart: always
    depends_on:
      - master
    mem_limit: 256m
    hostname: rmqha_node2
    volumes:
      - "./volumes/rmqha_slave/cluster_entrypoint.sh:/usr/local/bin/cluster_entrypoint.sh"
    entrypoint: "/usr/local/bin/cluster_entrypoint.sh"
    command: "rabbitmq-server"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=rmqha_node2
      - RABBITMQ_HOSTNAME=rmqha_node2
      - RABBITMQ_NODENAME=rabbit
      - RMQHA_RAM_NODE=true
