version: "2"
services:
  slave2:
    image: rabbitmq:3.7-management
    container_name: rmqha_node2
    restart: always
    mem_limit: 1024m
    hostname: rmqha_node2
    volumes:
      - "./volumes/rmqha_slave/cluster_entrypoint.sh:/usr/local/bin/cluster_entrypoint.sh"
    entrypoint: "/usr/local/bin/cluster_entrypoint.sh"
    command: "rabbitmq-server"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=rmqha_node2
      - RABBITMQ_HOSTNAME=rmqha_node2
      - RABBITMQ_NODENAME=rabbit
      - RMQHA_RAM_NODE=true
    extra_hosts:
      - "rmqha_node0:172.17.0.201"
      - "rmqha_node1:172.17.0.202"
    network_mode: "host"
