version: '2'
services:
  mysql:
    #image: registry.cn-shenzhen.aliyuncs.com/whb/mysql:5.7
    image: registry.cn-shenzhen.aliyuncs.com/whb/mysql:5.7.23
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234*
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/config/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
