version: '2'
services:
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/whb/redis:4-alpine
    command: redis-server
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./data/redis/data:/data
